menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/2396383073
    GitHub: https://github.com/jvsheng
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-71060212-1

# Copyright Infomation
startyear: 2017
